# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iBrary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iBrary
  pod 'GoogleSignIn'

  target 'iBraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iBrary-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iBrary-tvOS

  target 'iBrary-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
